In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [6]:
x = np.random.randint(10,size=(3,4,5))
print(x)

[[[2 9 6 8 0]
  [0 6 2 0 1]
  [6 1 5 6 9]
  [9 1 5 1 9]]

 [[7 1 4 8 6]
  [0 7 7 6 6]
  [5 0 7 6 2]
  [9 7 1 4 3]]

 [[8 9 4 6 7]
  [2 6 0 6 8]
  [9 7 3 9 6]
  [3 6 4 3 8]]]


In [7]:
x.itemsize

4

In [8]:
x.dtype

dtype('int32')

In [9]:
x = np.random.randint(10,20,size=(4,3))
print(x)

[[15 10 19]
 [15 19 13]
 [19 16 18]
 [12 17 18]]


In [10]:
print(x[0][0])

15


In [11]:
print(x[1][2])

13


In [12]:
print(x[1,2])

13


In [13]:
x[0,0] = 12

In [14]:
x

array([[12, 10, 19],
       [15, 19, 13],
       [19, 16, 18],
       [12, 17, 18]])

In [15]:
x[-1,-1]

18

In [17]:
x[-2,-3]

19

In [18]:
x = np.random.randint(10,20,size=(4,3))
print(x)

[[16 16 19]
 [16 14 18]
 [18 18 12]
 [18 14 17]]


In [19]:
x = np.random.randint(10,20,size=(4,3))
print(x)

[[18 10 17]
 [13 14 11]
 [17 16 18]
 [14 18 19]]


In [20]:
np.random.seed()
x = np.random.randint(10,20,size=(4,3))
print(x)

[[11 15 11]
 [13 11 11]
 [15 10 17]
 [18 16 15]]


In [31]:
np.random.seed(6)
y = np.random.randint(10,20,size=(4,3))
print(y)

[[19 13 14]
 [10 19 11]
 [19 11 14]
 [11 18 12]]


In [27]:
x = np.random.randint(10,20,size=(4,3))
print(x)

[[16 16 16]
 [14 12 15]
 [18 19 15]
 [11 17 19]]


In [23]:
x = np.random.randint(10,20,size=(4,3))
print(x)

[[15 13 18]
 [19 12 12]
 [10 13 13]
 [19 14 16]]


In [34]:
np.random.seed(2)
x = np.random.randint(10,20,size=(4,3))
print(x)

[[18 18 16]
 [12 18 17]
 [12 11 15]
 [14 14 15]]


In [35]:
np.random.seed(4)
x = np.random.randint(10,20,size=(4,3))
print(x)

[[17 15 11]
 [18 17 18]
 [12 19 17]
 [17 17 19]]


In [36]:
np.random.seed(2)
x = np.random.randint(10,20,size=(4,3))
print(x)

[[18 18 16]
 [12 18 17]
 [12 11 15]
 [14 14 15]]


In [4]:
import numpy as np
np.random.seed(9)
x = np.random.randint(10,20,size=(1,5))
print(x)

[[11 13 14 10 15]]


In [10]:
np.random.seed(9)
y = x[0,1:3]
print(y)

[13 14]


In [11]:
y[0] = 91
print(y)

[91 14]


In [12]:
print(x)

[[11 91 14 10 15]]


In [13]:
c = x[0,1:3].copy()
c[0] = 100
c

array([100,  14])

In [14]:
print(x)

[[11 91 14 10 15]]


In [16]:
np.random.seed(6)
a = np.random.randint(0,20,(3,4))
a

array([[10,  9,  3, 10],
       [13, 15, 10, 16],
       [ 1, 11, 13, 15]])

In [17]:
a.reshape(2,6)

array([[10,  9,  3, 10, 13, 15],
       [10, 16,  1, 11, 13, 15]])

ValueError: cannot reshape array of size 12 into shape (3,5)

 b = np.random.randint(0,20,(3,4))
c = np.random.randint(0,20,(4,4))
np.concatenate([a,b,c])

In [23]:
b = np.random.randint(0,20,(3,4))
c = np.random.randint(0,20,(4,4))
np.concatenate([a,b,c])

array([[10,  9,  3, 10],
       [13, 15, 10, 16],
       [ 1, 11, 13, 15],
       [ 2, 12, 10,  4],
       [17, 14,  3,  1],
       [ 4,  9, 14, 10],
       [ 6, 18, 15,  6],
       [18,  5, 15,  2],
       [12, 14, 14, 14],
       [12, 12,  1, 12]])

In [26]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
x + 5

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [28]:
x ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [30]:
y = x**2
y
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
y

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [32]:
np.log(y)

C:\Users\praka\AppData\Local\Temp\ipykernel_8620\3455148303.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y)


array([[      -inf, 0.        , 1.38629436],
       [2.19722458, 2.77258872, 3.21887582],
       [3.58351894, 3.8918203 , 4.15888308]])

In [33]:
y[0,0] = 2
y

array([[ 2,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [34]:
np.log(y)

array([[0.69314718, 0.        , 1.38629436],
       [2.19722458, 2.77258872, 3.21887582],
       [3.58351894, 3.8918203 , 4.15888308]])

In [39]:
arr = np.empty((2,2),dtype=np.int32)
arr

array([[ 476525185, -283820462],
       [-358301894, -617806943]])

In [40]:
arr[0,0] = 1
arr[0,1] = 2
arr[1,0] = 3
arr[1,1] = 4

In [41]:
print(arr)

[[1 2]
 [3 4]]


In [42]:
print(arr[0,0])

1


In [45]:
np.std(arr)

1.118033988749895

In [46]:
import numpy as np
np.__version__

'1.26.4'

In [47]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.full((3,3),fill_value=True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [49]:
x = np.arange(10)
x > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [50]:
x[x>5]

array([6, 7, 8, 9])

In [51]:
x[x>5] = 100

In [52]:
x

array([  0,   1,   2,   3,   4,   5, 100, 100, 100, 100])

In [53]:
y = x.copy()
y[y>0] = 101
y

array([  0, 101, 101, 101, 101, 101, 101, 101, 101, 101])

array([  0,   1,   2,   3,   4,   5, 100, 100, 100, 100])

In [71]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
y = x[1:4]
y

array([1, 2, 3])

In [76]:
np.setdiff1d(y,x)

array([], dtype=int32)

In [81]:
y = x.copy()
y[0] = 100
np.where(x==y)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [83]:
x[(x>=5) & (x<=9)]

array([5, 6, 7, 8, 9])

In [88]:
x = np.random.uniform(5,10,(3,3))
x

array([[8.30004909, 9.22213669, 8.01933278],
       [7.93606845, 5.58516518, 8.55225168],
       [6.02261629, 7.45183897, 5.18304265]])

In [91]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
x[...] = x**2
x

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [93]:
x**3

array([[     0,      1,     64],
       [   729,   4096,  15625],
       [ 46656, 117649, 262144]], dtype=int32)

In [94]:
x

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [99]:
import os
print(os.getcwd())

C:\Users\praka\OneDrive\Desktop


In [98]:
os.chdir('C:/Users/praka/OneDrive/Desktop')

In [127]:
names = np.array([],dtype="object")

with open("example.txt","a") as wr:
    wr.write("\nshani")

with open("example.txt","r")as rd:
    for line in rd:
        names = np.append(names,line[0:-1])
print(names)

['ramana reddy' 'chenna Lakshmi' 'guru prakash' 'pushpa harshitha' 'shani'
 'shani' '' 'shan']


In [128]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [145]:
x[[[0,2],[0,2]],[[0,0],[2,2]]]

array([[0, 6],
       [2, 8]])

In [150]:
print(x[(x > 4)])

[5 6 7 8]


In [147]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [151]:
x[x%2!=0]

array([1, 3, 5, 7])

In [159]:
x = np.arange(6).reshape(2,3)
y =  np.arange(4).reshape(4,1)
print(y)
print(x+y)

[[0]
 [1]
 [2]
 [3]]


ValueError: operands could not be broadcast together with shapes (2,3) (4,1) 

In [168]:
print(x[[0,1],:])

[[0 1 2]
 [3 4 5]]


In [172]:
x = np.random.randint(5,10,(2,2))
y = np.random.randint(5,10,(2,2))
print(x,y)
res = np.matmul(x,y)
print(res)

[[8 7]
 [6 5]] [[5 6]
 [5 5]]
[[75 83]
 [55 61]]


In [175]:
z = x.T
print(x)
print(z)

[[8 7]
 [6 5]]
[[8 6]
 [7 5]]


In [184]:
ang = np.array([0,30,45,60,90])
print(np.cot(ang))

AttributeError: module 'numpy' has no attribute 'cot'

In [185]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [186]:
print(np.exp(x))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [188]:
y = np.arange(2,7)
y

array([2, 3, 4, 5, 6])

In [190]:
print(x<y)

[ True  True  True  True  True]


In [191]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [193]:
print(np.append(x,5))
x

[0 1 2 3 4 5 6 7 8 9 5]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
x[...] = np.insert(x,1,100)
print(r)

ValueError: could not broadcast input array from shape (11,) into shape (10,)

In [195]:
r = np.delete(x,1)
print(r)

[0 2 3 4 5 6 7 8 9]


In [198]:
r = np.array_split(x,4)
print(r)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]


In [51]:
import numpy as np
import os

os.chdir("C:/Users/praka/Downloads")

arr = np.genfromtxt("nyc_taxis.csv",delimiter=',',dtype=float,skip_header=1)

dis = arr[:,7]

tim = arr[:,8] / 3600

s = np.array([dis/tim])

print(np.mean(s))

32.24258580925573


In [63]:
feb_rides = arr[:,1]

f = feb_rides == 2
print(len(feb_rides[f]))

13333


In [64]:
tip = arr[:,12]
tips = tip>50
print(len(tip[tips]))

16


In [65]:
jfk = arr[:,6]
drop = jfk == 2
print(len(jfk[drop]))

11832


In [116]:
ar = np.random.randint(10,20,(2,2))
r = ar.copy()
print(ar)
print(np.sum(ar))

[[12 14]
 [17 16]]
59


In [113]:
np.random.seed(0)
dr = np.random.randint(10,20,(2,2))
print(dr)
print(np.sum(dr))

[[15 10]
 [13 13]]
51


In [114]:
print(r)
print(np.sum(r))

[[17 19]
 [13 15]]
64
